"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
export function MockInterviewPanel() {
  const [role,setRole]=useState("AI Engineer"),[when,setWhen]=useState(""),[answer,setAnswer]=useState(""),[active,setActive]=useState<any>(null),[message,setMessage]=useState("");
  const q=useQuery({queryKey:["mock-interviews"],queryFn:()=>api("/mock-interviews")}); const current=active?.turns?.[active.turns.length-1];
  async function schedule(e:React.FormEvent){e.preventDefault();try{await api("/mock-interviews",{method:"POST",body:JSON.stringify({target_role:role,scheduled_at:new Date(when).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,question_count:5,difficulty:"mixed"})});setWhen("");q.refetch();setMessage("Interview scheduled.")}catch(e){setMessage(e instanceof Error?e.message:"Could not schedule interview.")}}
  async function start(i:any){setActive(await api(`/mock-interviews/${i.id}/start`,{method:"POST"}));q.refetch()}
  async function submit(){if(!answer.trim())return;setActive(await api(`/mock-interviews/${active.id}/answer`,{method:"POST",body:JSON.stringify({answer})}));setAnswer("");q.refetch()}
  return <div className="content-grid two-col"><section className="panel"><span className="eyebrow">PRACTICE LAB</span><h1>Mock interviews, on your time.</h1><p>Schedule practice and receive feedback after every answer.</p><form onSubmit={schedule} className="stack-form"><label>Target role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Start time<input type="datetime-local" required value={when} onChange={e=>setWhen(e.target.value)}/></label><button className="button primary">Schedule practice</button></form>{message&&<p className="form-note">{message}</p>}</section><section className="panel"><span className="eyebrow">UPCOMING SESSIONS</span>{q.data?.length?q.data.map((i:any)=><div className="learning-row" key={i.id}><div><h3>{i.target_role}</h3><p>{new Date(i.scheduled_at).toLocaleString()} · {i.status}</p></div>{i.status==="scheduled"&&<button className="button secondary" onClick={()=>start(i)}>Start</button>}</div>):<p className="muted">No interviews scheduled yet.</p>}{active&&current&&<div className="assistant-card"><strong>Question {active.turns.length} of {active.question_count}</strong><p>{current.question}</p><textarea aria-label="Your answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Situation, action, result…"/><button className="button primary" onClick={submit}>Submit answer</button>{current.feedback?.summary&&<p className="form-note">{current.feedback.summary}</p>}</div>}</section></div>;
}
