export const demoJobs = [
  {
    id: "j1",
    company: "Meridian Labs",
    initial: "M",
    role: "Junior AI Engineer",
    location: "Bengaluru",
    type: "Hybrid",
    salary: "₹8–12 LPA",
    score: 91,
    skills: ["Python", "FastAPI", "RAG"],
    gap: "Docker",
    color: "mint",
  },
  {
    id: "j2",
    company: "Forma Intelligence",
    initial: "f",
    role: "GenAI Engineer",
    location: "Remote, India",
    type: "Remote",
    salary: "₹10–16 LPA",
    score: 87,
    skills: ["LangGraph", "Python", "LLMs"],
    gap: "AWS",
    color: "lilac",
  },
  {
    id: "j3",
    company: "Northstar Analytics",
    initial: "n",
    role: "Machine Learning Engineer",
    location: "Pune",
    type: "Hybrid",
    salary: "₹7–11 LPA",
    score: 82,
    skills: ["Python", "Scikit-learn", "SQL"],
    gap: "CI/CD",
    color: "peach",
  },
  {
    id: "j4",
    company: "Canopy Systems",
    initial: "c",
    role: "Applied AI Engineer",
    location: "Mumbai",
    type: "Onsite",
    salary: "₹8–14 LPA",
    score: 78,
    skills: ["FastAPI", "PostgreSQL", "RAG"],
    gap: "AWS",
    color: "mint",
  },
];
export const trend = [
  { week: "Aug 03", match: 59 },
  { week: "Aug 10", match: 65 },
  { week: "Aug 17", match: 62 },
  { week: "Aug 24", match: 73 },
  { week: "Aug 31", match: 76 },
  { week: "Sep 07", match: 82 },
];
export const navigation = [
  { label: "Overview", slug: "dashboard", icon: "overview" },
  { label: "AI Career Assistant", slug: "assistant", icon: "assistant" },
  { label: "Job Discovery", slug: "jobs", icon: "jobs" },
  { label: "Job Matches", slug: "matches", icon: "matches" },
  { label: "Applications", slug: "applications", icon: "applications" },
  { label: "Practice Interviews", slug: "interviews", icon: "interviews" },
  { label: "Resume Studio", slug: "resume", icon: "resume" },
  { label: "Skill Intelligence", slug: "skills", icon: "skills" },
  { label: "Career Analytics", slug: "analytics", icon: "analytics" },
  { label: "Notifications", slug: "notifications", icon: "notifications" },
  { label: "Profile", slug: "profile", icon: "profile" },
  { label: "Settings", slug: "settings", icon: "settings" },
];
